package com.taptime.game.model

import androidx.compose.ui.graphics.Color

enum class SkinShape {
    CIRCLE,
    STAR,
    PIXEL,
    HEXAGON,
    DIAMOND,
}

data class ThemeColors(
    val standardFill: Color,
    val standardGlow: Color,
    val dangerFill: Color,
    val dangerGlow: Color,
    val extraLifeFill: Color,
    val extraLifeGlow: Color,
    val gridColor: Color,
    val bgTop: Color,
    val bgBottom: Color,
    val accent: Color,
)

data class GameTheme(
    val id: String,
    val name: String,
    val price: Int,
    val description: String,
    val shape: SkinShape,
    val colors: ThemeColors,
)

private fun c(r: Float, g: Float, b: Float) = Color(r, g, b)

object ThemeCatalog {
    val allThemes: List<GameTheme> = listOf(
        GameTheme(
            id = "neon_circle",
            name = "Neon Default",
            price = 0,
            description = "Classic cyan neon rings",
            shape = SkinShape.CIRCLE,
            colors = ThemeColors(
                standardFill = c(0f, 0.92f, 1f),
                standardGlow = c(0f, 0.75f, 1f),
                dangerFill = c(1f, 0.18f, 0.32f),
                dangerGlow = c(1f, 0.28f, 0.42f),
                extraLifeFill = c(1f, 0.82f, 0.05f),
                extraLifeGlow = c(1f, 0.72f, 0.1f),
                gridColor = c(0f, 0.35f, 0.55f),
                bgTop = c(0.03f, 0.03f, 0.09f),
                bgBottom = c(0.01f, 0.01f, 0.03f),
                accent = c(0f, 0.92f, 1f),
            ),
        ),
        GameTheme(
            id = "neon_star",
            name = "Neon Star",
            price = 10_000,
            description = "Brilliant blue star bursts",
            shape = SkinShape.STAR,
            colors = ThemeColors(
                standardFill = c(0.3f, 0.6f, 1f),
                standardGlow = c(0.2f, 0.5f, 1f),
                dangerFill = c(1f, 0.18f, 0.32f),
                dangerGlow = c(1f, 0.28f, 0.42f),
                extraLifeFill = c(1f, 0.82f, 0.05f),
                extraLifeGlow = c(1f, 0.72f, 0.1f),
                gridColor = c(0.15f, 0.25f, 0.6f),
                bgTop = c(0.02f, 0.03f, 0.12f),
                bgBottom = c(0.01f, 0.01f, 0.05f),
                accent = c(0.3f, 0.6f, 1f),
            ),
        ),
        GameTheme(
            id = "retro_pixel",
            name = "Retro Pixel",
            price = 5_000,
            description = "8-bit green block aesthetic",
            shape = SkinShape.PIXEL,
            colors = ThemeColors(
                standardFill = c(0.2f, 1f, 0.4f),
                standardGlow = c(0.15f, 0.8f, 0.3f),
                dangerFill = c(1f, 0.3f, 0.2f),
                dangerGlow = c(0.9f, 0.2f, 0.15f),
                extraLifeFill = c(1f, 0.9f, 0.2f),
                extraLifeGlow = c(0.9f, 0.8f, 0.15f),
                gridColor = c(0.05f, 0.25f, 0.1f),
                bgTop = c(0.02f, 0.05f, 0.02f),
                bgBottom = c(0.01f, 0.02f, 0.01f),
                accent = c(0.2f, 1f, 0.4f),
            ),
        ),
        GameTheme(
            id = "cyberpunk_pink",
            name = "Cyberpunk Pink",
            price = 15_000,
            description = "Hot pink/magenta neon overload",
            shape = SkinShape.CIRCLE,
            colors = ThemeColors(
                standardFill = c(1f, 0.2f, 0.7f),
                standardGlow = c(1f, 0.15f, 0.6f),
                dangerFill = c(0.6f, 0.1f, 0.9f),
                dangerGlow = c(0.5f, 0.05f, 0.85f),
                extraLifeFill = c(0.2f, 1f, 0.9f),
                extraLifeGlow = c(0.15f, 0.9f, 0.8f),
                gridColor = c(0.35f, 0.08f, 0.25f),
                bgTop = c(0.06f, 0.01f, 0.05f),
                bgBottom = c(0.02f, 0.01f, 0.02f),
                accent = c(1f, 0.2f, 0.7f),
            ),
        ),
        GameTheme(
            id = "hex_grid",
            name = "Hex Grid",
            price = 25_000,
            description = "Purple honeycomb precision",
            shape = SkinShape.HEXAGON,
            colors = ThemeColors(
                standardFill = c(0.65f, 0.35f, 1f),
                standardGlow = c(0.55f, 0.25f, 0.9f),
                dangerFill = c(1f, 0.18f, 0.32f),
                dangerGlow = c(1f, 0.28f, 0.42f),
                extraLifeFill = c(1f, 0.82f, 0.05f),
                extraLifeGlow = c(1f, 0.72f, 0.1f),
                gridColor = c(0.25f, 0.12f, 0.45f),
                bgTop = c(0.05f, 0.02f, 0.1f),
                bgBottom = c(0.02f, 0.01f, 0.05f),
                accent = c(0.65f, 0.35f, 1f),
            ),
        ),
        GameTheme(
            id = "emerald_hack",
            name = "Emerald Hack",
            price = 30_000,
            description = "Matrix-green hacker terminal",
            shape = SkinShape.CIRCLE,
            colors = ThemeColors(
                standardFill = c(0.1f, 1f, 0.5f),
                standardGlow = c(0.08f, 0.85f, 0.4f),
                dangerFill = c(1f, 0.3f, 0.1f),
                dangerGlow = c(0.9f, 0.2f, 0.08f),
                extraLifeFill = c(0.3f, 0.9f, 1f),
                extraLifeGlow = c(0.2f, 0.8f, 0.95f),
                gridColor = c(0.03f, 0.25f, 0.12f),
                bgTop = c(0.01f, 0.05f, 0.03f),
                bgBottom = c(0.01f, 0.02f, 0.01f),
                accent = c(0.1f, 1f, 0.5f),
            ),
        ),
        GameTheme(
            id = "diamond",
            name = "Diamond",
            price = 50_000,
            description = "Faceted gold luxury gems",
            shape = SkinShape.DIAMOND,
            colors = ThemeColors(
                standardFill = c(1f, 0.85f, 0.3f),
                standardGlow = c(1f, 0.75f, 0.2f),
                dangerFill = c(1f, 0.25f, 0.25f),
                dangerGlow = c(1f, 0.2f, 0.2f),
                extraLifeFill = c(0.4f, 1f, 0.6f),
                extraLifeGlow = c(0.3f, 0.9f, 0.5f),
                gridColor = c(0.3f, 0.22f, 0.05f),
                bgTop = c(0.06f, 0.04f, 0.02f),
                bgBottom = c(0.02f, 0.01f, 0.01f),
                accent = c(1f, 0.85f, 0.3f),
            ),
        ),
        GameTheme(
            id = "magma_flow",
            name = "Magma Flow",
            price = 60_000,
            description = "Molten orange inferno theme",
            shape = SkinShape.CIRCLE,
            colors = ThemeColors(
                standardFill = c(1f, 0.45f, 0.1f),
                standardGlow = c(1f, 0.35f, 0.05f),
                dangerFill = c(0.35f, 0.05f, 0.05f),
                dangerGlow = c(0.5f, 0.1f, 0.1f),
                extraLifeFill = c(1f, 0.95f, 0.3f),
                extraLifeGlow = c(1f, 0.9f, 0.2f),
                gridColor = c(0.3f, 0.08f, 0.03f),
                bgTop = c(0.06f, 0.02f, 0.01f),
                bgBottom = c(0.03f, 0.01f, 0.01f),
                accent = c(1f, 0.45f, 0.1f),
            ),
        ),
    )

    fun theme(id: String): GameTheme = allThemes.firstOrNull { it.id == id } ?: allThemes.first()
}
